CREATE DATABASE IF NOT EXISTS ordinateur CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ordinateur;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'bonjour';
GRANT ALL PRIVILEGES ON ordinateur.* TO 'user'@'%';
FLUSH PRIVILEGES;
